A	h origin main
A	public/assets/preset-thumbs/th-bw.svg
M	public/assets/preset-thumbs/th-igloo.svg
A	public/assets/preset-thumbs/th-pinky.svg
A	public/assets/preset-thumbs/th-purp.svg
A	public/assets/preset-thumbs/th-redecho.svg
A	public/assets/preset-thumbs/th-seafoam.svg
M	public/assets/preset-thumbs/th-slap.svg
M	public/assets/preset-thumbs/th-sunkist.svg
M	src/App.tsx
A	src/assets/logos/stizak copy.svg
A	src/assets/logos/stizak-wh.svg
M	src/assets/logos/stizak.svg
M	src/components/GraffitiDisplay.tsx.bak
M	src/components/GraffitiDisplay/EmptyState.tsx
M	src/components/InputForm.tsx
M	src/components/ModernCustomizationToolbar.tsx
M	src/components/ModernInputForm.tsx
M	src/components/ModernStyleSelector.tsx
M	src/components/PresetCard.tsx
M	src/components/StyleSelector.tsx
A	src/components/style-selector-concepts/StyleSelectorConcept1.tsx
A	src/components/style-selector-concepts/StyleSelectorConcept2.tsx
A	src/components/style-selector-concepts/StyleSelectorConcept3.tsx
A	src/components/style-selector-concepts/StyleSelectorConcept4.tsx
A	src/components/style-selector-concepts/StyleSelectorConcept5.tsx
A	src/components/style-selector-concepts/StyleSelectorDemoRoute.tsx
A	src/components/style-selector-concepts/StyleSelectorShowcase.tsx
A	src/components/style-selector-concepts/index.ts
A	src/components/ui/button.tsx
M	src/components/ui/color-picker.tsx
A	src/components/ui/dialog.tsx
A	src/components/ui/input.tsx
M	src/data/letterRules.ts
M	src/data/stylePresets.ts
